### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by treiher** [treiher/valens#25]
### Feature Specification

- Notifications can be enabled in the settings.
- A notification is shown when going to the next section during a guided training session.

### APIs

- [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) (supported by Firefox for Android and Safari on iOS, not supported by Chrome Android, Opera Android, Samsung Internet)
- [ServiceWorkerRegistration.showNotification()](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification) (supported by all common mobile browsers)

**Comment by senier** [comment]
Apparently this is implemented already in `0.2.1dev101`. I can see those notifications on the Desktop (e.g. a Gnome notification on Gnome Web). However, I'm unable to get this working on Android 13. In Fennec, the notifications setting says "Denied" and I don't see a way how to change that. In Chromium, I can grant notification permissions and it says "Granted". However, I do not see any notifications.

**Comment by treiher** [comment]
The existing implementation uses the Notification API that on Android is only fully supported by Firefox on Android (see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Notification#browser_compatibility)). On unsupported browsers there will be no notifications despite granted permissions. Fennec is based on Firefox and thus also supported. If "Denied" is displayed, the notification permission has been set to "Blocked". Unfortunately, if the permission request has been denied once, it is not possible to request the notification permission again, as the browser just ignores further requests from the app. The notification permission must be changed in the browser settings:

1. Open Valens in Fennec.
2. Tap on lock symbol in address bar.
3. Change settings for "Notification".

I will add a description to the settings dialog to make the user aware of this.

**Comment by senier** [comment]
Thanks for the explanation! I didn't know that the notification settings hide behind this lock in Firefox (in Chromium, this can be changed in the regular Android notification settings).

As an additional complication, Fennec seems to strictly block notification in private tabs. This cannot be changed (i.e. there are no notification settings behind the lock symbol for private tabs). I supposed, I must have opened Valens in a private tab first, the permissions got rejected automatically and then this was fixed even in normal tabs.

In a regular tab, Fennec now produces the expected notifications (after changing the permissions) :+1:
